# Importing the necessary libraries

In [18]:
import time
import numpy as np
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: Qt5Agg


# Initialize w with random value 
___

In [19]:
 w=np.array([[1],[-0.001]])

In [23]:
def plot(x,y,w,show= None ,curr_x1=None, curr_x2= None ,correct= None):
    plt.clf()
    if(show!= None):
        plt.title('Press any key if done else click')
    plt.xlim((-1,11))
    plt.ylim((-1,11))
    max_coordinates = np.amax(x_original,axis=0)
    #c_dict= {-1:'red',1:'blue'}
    #plt.scatter(x[:,0], x[:,1])
   
    for count,val in enumerate(x_original):
        if y[0][count]==-1:
            plt.scatter(val[0],val[1],color='red')
        else:
            plt.scatter(val[0],val[1],color='blue')
            
    if(correct == True and curr_x1!= None and curr_x2 != None):       
        plt.scatter(curr_x1,curr_x2,s = 100, color = 'green')
    elif(correct == False and curr_x1!= None and curr_x2 != None):
        plt.scatter(curr_x1,curr_x2,s = 100, color = 'white',marker = 'x')     
            
        
    m = -w[0]/w[1]
    #max_coordinates = np.amax(x_original,axis=0)
    x_line= [[0.,0.],[10,10]]
    #print(x_line)
    y_line = m*x_line
    plt.plot(x_line,y_line)
    plt.show()

# Loading the dataset
---

In [24]:
def tellme(s):
    print(s)
    plt.title(s, fontsize=16)
    plt.draw()

In [ ]:
plt.clf()
plt.setp(plt.gca(), autoscale_on=False)
tellme('click to begin')

plt.waitforbuttonpress()

while True:
    plt.clf()
    plt.rcParams['figure.figsize'] = (12,8)
    plt.xlim((0,10))
    plt.ylim((0,10))
    pts = []
    pts1 = []
    y = []
    tellme('Select Class 1 points, press enter when done')
    pts = np.asarray(plt.ginput(-1, timeout=-1))
      
    tellme('click to begin to Class 2 points,press enter when done')
    plt.waitforbuttonpress()
    pts1 = np.asarray(plt.ginput(-1, timeout=-1))
    y1 = np.ones((pts.shape[0]))
    y2 = np.empty((pts1.shape[0]))
    y2.fill(-1)
    y = np.append(y1,y2)
    y=y.reshape(1,y.shape[0])
    x_original = np.concatenate((pts,pts1))
    x = x_original.T
    tellme('Happy? Key click for yes, mouse click for no')
    plot(x_original,y,w,show=1)
    if plt.waitforbuttonpress():
        break

click to begin
Select Class 1 points, press enter when done
click to begin to Class 2 points,press enter when done
Happy? Key click for yes, mouse click for no


# Calculate the Cost Function
___

Our objective is to minimize the cost funtion

$$ J(w) = \frac{1}{2}||w^{2}|| +
\frac{C}{N} \sum_{i = 1}^m (max (1- y^{(i)} (w x^{(i)}+ b), 0))$$


In [6]:
def cost_function(x,y,w,C):
    N = y.shape[1]
    regularization_loss = 0.5*np.linalg.norm(w)
    hinge_loss = (C/N) * np.sum(np.maximum(1- y*np.dot(w.T,x),0))
    cost = regularization_loss + hinge_loss
    return cost

In [7]:
np.maximum(1-y*np.dot(w.T,x),0)

array([[ 0.        ,  0.        ,  0.12096516,  0.21296993,  0.19397414,
         0.45430879,  0.45346242,  0.        ,  0.        ,  0.        ,
         0.44443381,  0.48280001,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.13122865,  0.17731428,
         0.92439202,  0.        ,  0.        ,  0.        ,  0.        ,
        10.2900114 ,  9.44430559,  8.53182559,  9.61481384, 10.56054911,
        10.60200944,  9.86887206,  9.43855641,  9.99551961,  9.94072941,
        10.6120093 , 10.68683591,  8.58676841,  8.08952596,  8.75390504,
         8.75390504,  9.25173024,  8.98857897,  9.33815233,  9.92369   ,
        10.58306915, 10.3138357 , 10.29935421, 10.37603112, 10.80554202,
         9.87949629]])

In [8]:
np.sum(np.maximum(1-y*np.dot(w.T,x),0))/y.shape[1]

4.591526274544708

In [9]:
cost_function(x,y,w,1000)

4592.026274794708

# Calculate the grads
___

In [10]:
w

array([[ 1.   ],
       [-0.001]])

In [11]:
plot(x_original,y,w)

In [12]:
def grads(x,y,w,C):
    N = y.shape[1]
    dw = np.zeros_like(w)
    
    distances = 1- (y*np.dot(w.T,x))
    
    for index, d in enumerate(distances[0]):
        
        if(max(d,0) == 0):
            dwi= w
            
        else:
            xi= [[x[0][index]], [x[1][index]]]
            yi = y[0][index]
            
            dwi= w - (C * np.multiply(yi , xi))
        dw = dw+dwi
                     
    assert(dw.shape == w.shape)
    return dw

In [13]:
steps = 2000
lr = 0.001
c = 1000
N = y.shape[1]
prev = cost_function(x,y,w,c)
print('Initial cost', cost_function(x,y,w,c))
for step in range(steps):
    w = w- lr/N*grads(x,y,w,c)
    if(step %100 == 0):
        print('Cost after',step,'iteration',cost_function(x,y,w,c))
        '''
        if(cost_function(x,y,w,c)>prev):
            break
        else:
            prev = cost_function(x,y,w,c)
        #plot(x,y,w)
        '''

Initial cost 4592.026274794708
Cost after 0 iteration 3501.8273586415376
Cost after 100 iteration 1.9358316372919142
Cost after 200 iteration 1.751525263555998
Cost after 300 iteration 1.5847663039367363
Cost after 400 iteration 1.4338841068123767
Cost after 500 iteration 1.2973670797149928
Cost after 600 iteration 1.1738475456499708
Cost after 700 iteration 1.0620880412127944
Cost after 800 iteration 0.9609689192327182
Cost after 900 iteration 0.8694771317421115
Cost after 1000 iteration 0.7866960808952143
Cost after 1100 iteration 0.7117964361591212
Cost after 1200 iteration 0.6575042076560245
Cost after 1300 iteration 0.5949046437813921
Cost after 1400 iteration 0.5382650499748819
Cost after 1500 iteration 0.4870179902830411
Cost after 1600 iteration 0.44065005311119637
Cost after 1700 iteration 0.39869670768024945
Cost after 1800 iteration 0.36073765018917986
Cost after 1900 iteration 0.3263925930594221


In [14]:
w

array([[-0.41661252],
       [ 0.4195025 ]])

In [15]:
plot(x,y,w)

In [16]:
np.dot(w.T,x)

array([[ 2.31778207,  2.01135418,  3.01242757,  2.17853453,  2.65906574,
         2.02904195,  1.67398517,  1.7383031 ,  2.56931602,  3.32209722,
         3.51933731,  2.71543117,  1.83209068,  2.57669091,  2.84966667,
         2.51339254,  2.90197678,  3.24230124,  2.84067963,  2.36824907,
         1.6798736 ,  1.81463386,  1.42516822,  1.68510911,  1.3030862 ,
         2.07951395,  1.32392294,  1.81395597,  2.13785066,  1.96890752,
        -2.05006303, -2.14547274, -2.39332298, -3.26317667, -2.88381043,
        -3.37789877, -2.81661236, -2.55011513, -2.43326362, -1.98014048,
        -1.93998884, -2.34912601, -2.91047276, -2.73238944, -2.61377015,
        -2.61377015, -3.0363188 , -2.48476017, -2.67691539, -3.28137672,
        -3.88171239, -3.59510169, -3.15295683, -1.52186214, -1.45076439,
        -1.64062957]])

In [17]:
x

array([[1.82795699, 1.59946237, 0.88709677, 0.79301075, 0.81317204,
        0.55107527, 0.55107527, 1.27688172, 2.78897849, 1.13575269,
        0.56451613, 0.52419355, 2.37903226, 1.29032258, 1.96236559,
        3.10483871, 2.31182796, 1.59274194, 1.59274194, 2.41935484,
        1.79435484, 1.3172043 , 1.52553763, 0.87365591, 0.8266129 ,
        0.08064516, 3.86424731, 4.46236559, 3.62903226, 3.26612903,
        9.29435484, 8.44758065, 7.53360215, 8.6155914 , 9.56317204,
        9.60349462, 8.87096774, 8.44086022, 8.99865591, 8.94489247,
        9.61693548, 9.69086022, 7.58736559, 7.09005376, 7.75537634,
        7.75537634, 8.25268817, 7.9905914 , 8.34005376, 8.92473118,
        9.58333333, 9.31451613, 9.30107527, 9.38172043, 9.81182796,
        8.8844086 ],
       [7.34043734, 6.38306138, 8.06193806, 5.98068598, 7.14618715,
        5.38406038, 4.53768454, 5.41181041, 8.89443889, 9.04706405,
        8.94993895, 6.99356199, 6.72993673, 7.42368742, 8.74181374,
        9.07481407, 9.21356